apiVersion: batch/v1
kind: Job
metadata:
  name: load-driver
  namespace: default
spec:
  template:
    # metadata:
    #   annotations:
    #     prometheus.io/scrape: "true"
    #     prometheus.io/port: "2113"
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-000.haiyen-273246.ntu-cloud.emulab.net
      restartPolicy: Never
      containers:
        - name: load-driver
          image: haiyen11231/load-driver:3.0
          args:
            [
              "--target",
              "worker.default.svc.cluster.local:50051",
              "--rps",
              "5",
              "--spin-ms",
              "100",
              "--duration",
              "12m",
              "--out",
              "/out/results.csv",
              "--metrics-port",
              "2113",
            ]
          ports:
            - containerPort: 2113
              name: metrics
          volumeMounts:
            - name: results
              mountPath: /out
      volumes:
        - name: results
          emptyDir: {}
