apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: load-driver-service
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: haiyen11231/lab-project-client:1.0
          name: client
