apiVersion: v1
kind: Service
metadata:
  name: worker-metrics
  namespace: default
  labels:
    app: worker
spec:
  ports:
    - name: metrics
      port: 2112
      targetPort: 2112
  selector:
    serving.knative.dev/service: worker
