// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/load_worker.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Duration of the busy-spin loop in milliseconds
	DurationMs    int64 `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_proto_load_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_load_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_load_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type WorkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Acknowledgment message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_proto_load_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_load_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_load_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_load_worker_proto protoreflect.FileDescriptor

const file_proto_load_worker_proto_rawDesc = "" +
	"\n" +
	"\x17proto/load_worker.proto\x12\vload_worker\".\n" +
	"\vWorkRequest\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\"(\n" +
	"\fWorkResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2Q\n" +
	"\n" +
	"LoadWorker\x12C\n" +
	"\fInvokeWorker\x12\x18.load_worker.WorkRequest\x1a\x19.load_worker.WorkResponseB\x04Z\x02./b\x06proto3"

var (
	file_proto_load_worker_proto_rawDescOnce sync.Once
	file_proto_load_worker_proto_rawDescData []byte
)

func file_proto_load_worker_proto_rawDescGZIP() []byte {
	file_proto_load_worker_proto_rawDescOnce.Do(func() {
		file_proto_load_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_load_worker_proto_rawDesc), len(file_proto_load_worker_proto_rawDesc)))
	})
	return file_proto_load_worker_proto_rawDescData
}

var file_proto_load_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_load_worker_proto_goTypes = []any{
	(*WorkRequest)(nil),  // 0: load_worker.WorkRequest
	(*WorkResponse)(nil), // 1: load_worker.WorkResponse
}
var file_proto_load_worker_proto_depIdxs = []int32{
	0, // 0: load_worker.LoadWorker.InvokeWorker:input_type -> load_worker.WorkRequest
	1, // 1: load_worker.LoadWorker.InvokeWorker:output_type -> load_worker.WorkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_load_worker_proto_init() }
func file_proto_load_worker_proto_init() {
	if File_proto_load_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_load_worker_proto_rawDesc), len(file_proto_load_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_load_worker_proto_goTypes,
		DependencyIndexes: file_proto_load_worker_proto_depIdxs,
		MessageInfos:      file_proto_load_worker_proto_msgTypes,
	}.Build()
	File_proto_load_worker_proto = out.File
	file_proto_load_worker_proto_goTypes = nil
	file_proto_load_worker_proto_depIdxs = nil
}
