// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/load_worker.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoadWorker_InvokeWorker_FullMethodName = "/load_worker.LoadWorker/InvokeWorker"
)

// LoadWorkerClient is the client API for LoadWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoadWorkerClient interface {
	InvokeWorker(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*WorkResponse, error)
}

type loadWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadWorkerClient(cc grpc.ClientConnInterface) LoadWorkerClient {
	return &loadWorkerClient{cc}
}

func (c *loadWorkerClient) InvokeWorker(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*WorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkResponse)
	err := c.cc.Invoke(ctx, LoadWorker_InvokeWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadWorkerServer is the server API for LoadWorker service.
// All implementations must embed UnimplementedLoadWorkerServer
// for forward compatibility.
type LoadWorkerServer interface {
	InvokeWorker(context.Context, *WorkRequest) (*WorkResponse, error)
	mustEmbedUnimplementedLoadWorkerServer()
}

// UnimplementedLoadWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadWorkerServer struct{}

func (UnimplementedLoadWorkerServer) InvokeWorker(context.Context, *WorkRequest) (*WorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeWorker not implemented")
}
func (UnimplementedLoadWorkerServer) mustEmbedUnimplementedLoadWorkerServer() {}
func (UnimplementedLoadWorkerServer) testEmbeddedByValue()                    {}

// UnsafeLoadWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadWorkerServer will
// result in compilation errors.
type UnsafeLoadWorkerServer interface {
	mustEmbedUnimplementedLoadWorkerServer()
}

func RegisterLoadWorkerServer(s grpc.ServiceRegistrar, srv LoadWorkerServer) {
	// If the following call pancis, it indicates UnimplementedLoadWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadWorker_ServiceDesc, srv)
}

func _LoadWorker_InvokeWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadWorkerServer).InvokeWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadWorker_InvokeWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadWorkerServer).InvokeWorker(ctx, req.(*WorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoadWorker_ServiceDesc is the grpc.ServiceDesc for LoadWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "load_worker.LoadWorker",
	HandlerType: (*LoadWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeWorker",
			Handler:    _LoadWorker_InvokeWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/load_worker.proto",
}
